version: "2.0"
services:
    web:
        build: web
        ports:
            - 3000:3000
        depends_on:
            - auth-svc

    auth-svc:
        build: auth-svc
        ports:
            - 8081:8081
        depends_on:
            - mysql
        environment:
            MYSQL_ENDPOINT: mysql
            MYSQL_DATABASE: spt
            MYSQL_USER: dev
            MYSQL_PASSWORD: coke

    mysql:
        image: mysql:5.7
        ports:
            - 3307:3306
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: coke
            MYSQL_USER: dev
            MYSQL_PASSWORD: coke
            MYSQL_DATABASE: spt
